import { Audiofile, Playlist } from "./media";

export const dummyAudiofiles: Audiofile[] = [
  {
    id: 1,
    filename: "track1.mp3",
    objects: ["object1", "object2"],
    title: "Sample Track 1",
    album: "Sample Album",
    playlist_id: 1,
    uploaded_at: "2024-01-01T12:00:00Z",
    uploaded_by_id: 101,
    uploaded_by_username: "user101",
    artists: ["Artist1", "Artist2"],
    duration: 215,
    track_number: 1,
    track_total: 10,
    genre: "Rock",
    bitrate: 320,
    mime_type: "audio/mpeg",
    format: "MP3",
    channels: 2,
    sample_rate: 44100,
  },
  {
    id: 2,
    filename: "track2.flac",
    objects: ["object3"],
    title: "Sample Track 2",
    album: "Another Album",
    playlist_id: 2,
    uploaded_at: "2024-02-02T15:30:00Z",
    uploaded_by_id: 102,
    uploaded_by_username: "user102",
    artists: ["Artist3"],
    duration: 300,
    track_number: 2,
    track_total: 8,
    genre: "Jazz",
    bitrate: 1000,
    mime_type: "audio/flac",
    format: "FLAC",
    channels: 2,
    sample_rate: 96000,
  },
  {
    id: 3,
    filename: "track3.wav",
    objects: ["object4", "object5"],
    title: null,
    album: "Unknown Album",
    playlist_id: 1,
    uploaded_at: "2024-03-03T10:15:00Z",
    uploaded_by_id: null,
    uploaded_by_username: null,
    artists: null,
    duration: null,
    track_number: null,
    track_total: null,
    genre: null,
    bitrate: null,
    mime_type: "audio/wav",
    format: "WAV",
    channels: 1,
    sample_rate: 44100,
  },
  {
    id: 4,
    filename: "track1.mp3",
    objects: ["object1", "object2"],
    title: "Sample Track 1",
    album: "Sample Album",
    playlist_id: 1,
    uploaded_at: "2024-01-01T12:00:00Z",
    uploaded_by_id: 101,
    uploaded_by_username: "user101",
    artists: ["Artist1", "Artist2"],
    duration: 215,
    track_number: 1,
    track_total: 10,
    genre: "Rock",
    bitrate: 320,
    mime_type: "audio/mpeg",
    format: "MP3",
    channels: 2,
    sample_rate: 44100,
  },
  {
    id: 5,
    filename: "track2.flac",
    objects: ["object3"],
    title: "Sample Track 2",
    album: "Another Album",
    playlist_id: 2,
    uploaded_at: "2024-02-02T15:30:00Z",
    uploaded_by_id: 102,
    uploaded_by_username: "user102",
    artists: ["Artist3"],
    duration: 300,
    track_number: 2,
    track_total: 8,
    genre: "Jazz",
    bitrate: 1000,
    mime_type: "audio/flac",
    format: "FLAC",
    channels: 2,
    sample_rate: 96000,
  },
  {
    id: 6,
    filename: "track3.wav",
    objects: ["object4", "object5"],
    title: null,
    album: "Unknown Album",
    playlist_id: 1,
    uploaded_at: "2024-03-03T10:15:00Z",
    uploaded_by_id: null,
    uploaded_by_username: null,
    artists: null,
    duration: null,
    track_number: null,
    track_total: null,
    genre: null,
    bitrate: null,
    mime_type: "audio/wav",
    format: "WAV",
    channels: 1,
    sample_rate: 44100,
  },
  {
    id: 7,
    filename: "track1.mp3",
    objects: ["object1", "object2"],
    title: "Sample Track 1",
    album: "Sample Album",
    playlist_id: 1,
    uploaded_at: "2024-01-01T12:00:00Z",
    uploaded_by_id: 101,
    uploaded_by_username: "user101",
    artists: ["Artist1", "Artist2"],
    duration: 215,
    track_number: 1,
    track_total: 10,
    genre: "Rock",
    bitrate: 320,
    mime_type: "audio/mpeg",
    format: "MP3",
    channels: 2,
    sample_rate: 44100,
  },
  {
    id: 8,
    filename: "track2.flac",
    objects: ["object3"],
    title: "Sample Track 2",
    album: "Another Album",
    playlist_id: 2,
    uploaded_at: "2024-02-02T15:30:00Z",
    uploaded_by_id: 102,
    uploaded_by_username: "user102",
    artists: ["Artist3"],
    duration: 300,
    track_number: 2,
    track_total: 8,
    genre: "Jazz",
    bitrate: 1000,
    mime_type: "audio/flac",
    format: "FLAC",
    channels: 2,
    sample_rate: 96000,
  },
  {
    id: 9,
    filename: "track3.wav",
    objects: ["object4", "object5"],
    title: null,
    album: "Unknown Album",
    playlist_id: 1,
    uploaded_at: "2024-03-03T10:15:00Z",
    uploaded_by_id: null,
    uploaded_by_username: null,
    artists: null,
    duration: null,
    track_number: null,
    track_total: null,
    genre: null,
    bitrate: null,
    mime_type: "audio/wav",
    format: "WAV",
    channels: 1,
    sample_rate: 44100,
  },
];

export const dummyPlaylists: Playlist[] = [
  {
    id: 1,
    name: "Chill Vibes",
    owner_id: 101,
    owner_username: "user101",
    created_at: "2024-01-10T09:30:00Z",
  },
  {
    id: 2,
    name: "Jazz Essentials",
    owner_id: 102,
    owner_username: "user102",
    created_at: "2024-02-15T14:45:00Z",
  },
  {
    id: 3,
    name: "Workout Mix",
    owner_id: 103,
    owner_username: "user103",
    created_at: "2024-03-20T08:00:00Z",
  },
];
