/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library/index'
import { Route as AuthenticatedLibraryPlaylistsPlaylistIdRouteImport } from './routes/_authenticated/library/playlists.$playlistId'
import { Route as AuthenticatedLibraryPlaylistsPlaylistIdIndexRouteImport } from './routes/_authenticated/library/playlists.$playlistId/index'
import { Route as AuthenticatedLibraryPlaylistsPlaylistIdUploadRouteImport } from './routes/_authenticated/library/playlists.$playlistId/upload'

const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryPlaylistsPlaylistIdRoute =
  AuthenticatedLibraryPlaylistsPlaylistIdRouteImport.update({
    id: '/library/playlists/$playlistId',
    path: '/library/playlists/$playlistId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryPlaylistsPlaylistIdIndexRoute =
  AuthenticatedLibraryPlaylistsPlaylistIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLibraryPlaylistsPlaylistIdRoute,
  } as any)
const AuthenticatedLibraryPlaylistsPlaylistIdUploadRoute =
  AuthenticatedLibraryPlaylistsPlaylistIdUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedLibraryPlaylistsPlaylistIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/library/playlists/$playlistId': typeof AuthenticatedLibraryPlaylistsPlaylistIdRouteWithChildren
  '/library/playlists/$playlistId/upload': typeof AuthenticatedLibraryPlaylistsPlaylistIdUploadRoute
  '/library/playlists/$playlistId/': typeof AuthenticatedLibraryPlaylistsPlaylistIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/home': typeof AuthenticatedHomeRoute
  '/': typeof AuthenticatedIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/library/playlists/$playlistId/upload': typeof AuthenticatedLibraryPlaylistsPlaylistIdUploadRoute
  '/library/playlists/$playlistId': typeof AuthenticatedLibraryPlaylistsPlaylistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/library/playlists/$playlistId': typeof AuthenticatedLibraryPlaylistsPlaylistIdRouteWithChildren
  '/_authenticated/library/playlists/$playlistId/upload': typeof AuthenticatedLibraryPlaylistsPlaylistIdUploadRoute
  '/_authenticated/library/playlists/$playlistId/': typeof AuthenticatedLibraryPlaylistsPlaylistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/complete-profile'
    | '/home'
    | '/library/'
    | '/library/playlists/$playlistId'
    | '/library/playlists/$playlistId/upload'
    | '/library/playlists/$playlistId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/complete-profile'
    | '/home'
    | '/'
    | '/library'
    | '/library/playlists/$playlistId/upload'
    | '/library/playlists/$playlistId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/complete-profile'
    | '/_authenticated/home'
    | '/_authenticated/'
    | '/_authenticated/library/'
    | '/_authenticated/library/playlists/$playlistId'
    | '/_authenticated/library/playlists/$playlistId/upload'
    | '/_authenticated/library/playlists/$playlistId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/playlists/$playlistId': {
      id: '/_authenticated/library/playlists/$playlistId'
      path: '/library/playlists/$playlistId'
      fullPath: '/library/playlists/$playlistId'
      preLoaderRoute: typeof AuthenticatedLibraryPlaylistsPlaylistIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/playlists/$playlistId/': {
      id: '/_authenticated/library/playlists/$playlistId/'
      path: '/'
      fullPath: '/library/playlists/$playlistId/'
      preLoaderRoute: typeof AuthenticatedLibraryPlaylistsPlaylistIdIndexRouteImport
      parentRoute: typeof AuthenticatedLibraryPlaylistsPlaylistIdRoute
    }
    '/_authenticated/library/playlists/$playlistId/upload': {
      id: '/_authenticated/library/playlists/$playlistId/upload'
      path: '/upload'
      fullPath: '/library/playlists/$playlistId/upload'
      preLoaderRoute: typeof AuthenticatedLibraryPlaylistsPlaylistIdUploadRouteImport
      parentRoute: typeof AuthenticatedLibraryPlaylistsPlaylistIdRoute
    }
  }
}

interface AuthenticatedLibraryPlaylistsPlaylistIdRouteChildren {
  AuthenticatedLibraryPlaylistsPlaylistIdUploadRoute: typeof AuthenticatedLibraryPlaylistsPlaylistIdUploadRoute
  AuthenticatedLibraryPlaylistsPlaylistIdIndexRoute: typeof AuthenticatedLibraryPlaylistsPlaylistIdIndexRoute
}

const AuthenticatedLibraryPlaylistsPlaylistIdRouteChildren: AuthenticatedLibraryPlaylistsPlaylistIdRouteChildren =
  {
    AuthenticatedLibraryPlaylistsPlaylistIdUploadRoute:
      AuthenticatedLibraryPlaylistsPlaylistIdUploadRoute,
    AuthenticatedLibraryPlaylistsPlaylistIdIndexRoute:
      AuthenticatedLibraryPlaylistsPlaylistIdIndexRoute,
  }

const AuthenticatedLibraryPlaylistsPlaylistIdRouteWithChildren =
  AuthenticatedLibraryPlaylistsPlaylistIdRoute._addFileChildren(
    AuthenticatedLibraryPlaylistsPlaylistIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
  AuthenticatedLibraryPlaylistsPlaylistIdRoute: typeof AuthenticatedLibraryPlaylistsPlaylistIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
  AuthenticatedLibraryPlaylistsPlaylistIdRoute:
    AuthenticatedLibraryPlaylistsPlaylistIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CompleteProfileRoute: CompleteProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
