import sample_icon from "./icon.jpg";
export const sample_results = [
  {
    id: 1,
    type: "song",
    name: "Donna Lee",
    album: "Dona Lee",
    artist: "Anthony Braxton",
    year: 1972,
    icon: sample_icon,
  },
  {
    id: 2,
    type: "album",
    name: "Dona Lee",
    artist: "Anthony Braxton",
    year: 1972,
    icon: sample_icon,
    songCount: 5,
  },
  {
    id: 3,
    type: "artist",
    icon: sample_icon,
    name: "Anthony Braxton",
  },
  {
    id: 4,
    type: "song",
    name: "Donna Lee",
    album: "Dona Lee",
    artist: "Anthony Braxton",
    year: 1972,
    icon: sample_icon,
  },
  {
    id: 5,
    type: "album",
    name: "Dona Lee",
    artist: "Anthony Braxton",
    year: 1972,
    icon: sample_icon,
    songCount: 5,
  },
  {
    id: 6,
    type: "artist",
    icon: sample_icon,
    name: "Anthony Braxton",
  },
  {
    id: 7,
    type: "song",
    name: "Donna Lee",
    album: "Dona Lee",
    artist: "Anthony Braxton",
    year: 1972,
    icon: sample_icon,
  },
  {
    id: 8,
    type: "album",
    name: "Dona Lee",
    artist: "Anthony Braxton",
    year: 1972,
    icon: sample_icon,
    songCount: 5,
  },
  {
    id: 9,
    type: "artist",
    icon: sample_icon,
    name: "Anthony Braxton",
  },
  {
    id: 10,
    type: "song",
    name: "Donna Lee",
    album: "Dona Lee",
    artist: "Anthony Braxton",
    year: 1972,
    icon: sample_icon,
  },
  {
    id: 11,
    type: "album",
    name: "Dona Lee",
    artist: "Anthony Braxton",
    year: 1972,
    icon: sample_icon,
    songCount: 5,
  },
  {
    id: 12,
    type: "artist",
    icon: sample_icon,
    name: "Anthony Braxton",
  },
];
